"""
app.py
------
Flask backend for the EURUSD LSTM Dashboard (Plotly edition).

Design note (changed from the original version): predictions are now
generated by a background scheduler (APScheduler) on a fixed interval,
independent of page views. The original version re-ran the full
subprocess -> fetch data -> reload model -> run inference pipeline on
EVERY page load and every 30-second auto-refresh, which is wasteful and
would hammer external data sources under any real traffic. Now the page
just reads the latest cached prediction_results.json.

Routes:
  GET  /          -> renders the dashboard page with embedded Plotly charts
  GET  /health    -> simple health check for deployment platforms
  POST /refresh   -> triggers an immediate prediction run, then redirects to /
"""

import json
import logging
import os
import sys
from datetime import datetime

from apscheduler.schedulers.background import BackgroundScheduler
from flask import Flask, jsonify, redirect, render_template_string, url_for

import lstm_core as core

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger("app")

app = Flask(__name__)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "lstm_model.pth")
RESULTS_PATH = os.path.join(BASE_DIR, "prediction_results.json")

# Refresh interval in seconds. Configurable via env var for deployment.
REFRESH_INTERVAL_SECONDS = int(os.environ.get("REFRESH_INTERVAL_SECONDS", "60"))

_model = None  # loaded lazily, once, on first use


def get_model():
    global _model
    if _model is None:
        _model = core.load_model(MODEL_PATH)
    return _model


def run_prediction_job():
    """Fetch data, run the model, and write prediction_results.json.
    Any failure is logged and swallowed so the scheduler keeps running."""
    try:
        model = get_model()
        raw_data, data_source = core.get_market_data()
        raw_data = raw_data.iloc[-core.REQUIRED_BARS:]
        feature_frame = core.build_feature_frame(raw_data)
        run = core.run_backtest_and_forecast(model, feature_frame)

        metrics = core.regression_metrics(run.true_prices, run.predicted_prices)
        dir_acc = core.directional_accuracy(run.true_prices, run.predicted_prices)

        results = {
            "predicted_prices": run.predicted_prices,
            "true_prices": run.true_prices,
            "timestamps": run.timestamps,
            "percent_change": run.percent_change,
            "next_prediction": run.next_prediction,
            "data_source": data_source,
            "mae": metrics["mae"],
            "rmse": metrics["rmse"],
            "directional_accuracy": dir_acc,
            "generated_at": datetime.now().isoformat(timespec="seconds"),
        }
        with open(RESULTS_PATH, "w") as f:
            json.dump(results, f)
        logger.info("Prediction refreshed. Source: %s", data_source)
    except Exception:
        logger.exception("Prediction job failed; keeping last known results.")


def load_results():
    if not os.path.exists(RESULTS_PATH):
        return None, "No predictions generated yet. Click Refresh Now or wait for the first scheduled run."
    try:
        with open(RESULTS_PATH) as f:
            return json.load(f), None
    except Exception as exc:
        return None, f"Failed to parse prediction_results.json: {exc}"


def build_charts(results):
    """Build Plotly chart HTML strings from prediction results."""
    import plotly.graph_objects as go

    timestamps = results["timestamps"]
    true_prices = results["true_prices"]
    pred_prices = results["predicted_prices"]
    EPS = 1e-10

    fig_price = go.Figure()
    fig_price.add_trace(go.Scatter(
        x=timestamps, y=true_prices, mode="lines+markers", name="Actual (normalised)",
        line=dict(color="#2e7d32", width=2), marker=dict(size=4),
    ))
    fig_price.add_trace(go.Scatter(
        x=timestamps, y=pred_prices, mode="lines+markers", name="Predicted (normalised)",
        line=dict(color="#1565c0", width=2, dash="dash"), marker=dict(size=4),
    ))
    fig_price.update_layout(
        title="True vs Predicted Close Price (normalised 0-1)",
        xaxis_title="Time (UTC)", yaxis_title="Normalised price",
        hovermode="x unified", legend=dict(orientation="h", y=1.08),
        margin=dict(l=50, r=20, t=60, b=50),
        plot_bgcolor="#fafafa", paper_bgcolor="#ffffff",
    )
    fig_price.update_xaxes(showgrid=True, gridcolor="#eeeeee")
    fig_price.update_yaxes(showgrid=True, gridcolor="#eeeeee")

    pct_true = [
        ((true_prices[i] - true_prices[i - 1]) / (abs(true_prices[i - 1]) + EPS)) * 100
        for i in range(1, len(true_prices))
    ]
    pct_pred = [
        ((pred_prices[i] - pred_prices[i - 1]) / (abs(pred_prices[i - 1]) + EPS)) * 100
        for i in range(1, len(pred_prices))
    ]

    fig_pct = go.Figure()
    fig_pct.add_trace(go.Bar(x=timestamps[1:], y=pct_true, name="Actual % change", marker_color="#2e7d32", opacity=0.75))
    fig_pct.add_trace(go.Bar(x=timestamps[1:], y=pct_pred, name="Predicted % change", marker_color="#1565c0", opacity=0.75))
    fig_pct.update_layout(
        title="Bar-by-Bar % Change: Actual vs Predicted",
        xaxis_title="Time (UTC)", yaxis_title="% change", barmode="group",
        hovermode="x unified", legend=dict(orientation="h", y=1.08),
        margin=dict(l=50, r=20, t=60, b=50),
        plot_bgcolor="#fafafa", paper_bgcolor="#ffffff",
    )
    fig_pct.update_xaxes(showgrid=True, gridcolor="#eeeeee")
    fig_pct.update_yaxes(showgrid=True, gridcolor="#eeeeee", zeroline=True, zerolinecolor="#aaa")

    price_html = fig_price.to_html(full_html=False, include_plotlyjs="cdn", div_id="priceChart")
    pct_html = fig_pct.to_html(full_html=False, include_plotlyjs=False, div_id="pctChart")
    return price_html, pct_html


PAGE_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>EURUSD LSTM Dashboard</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', sans-serif; background: #f0f2f5; margin: 0; padding: 24px 16px;
      display: flex; flex-direction: column; align-items: center;
    }
    .card {
      background: #fff; border-radius: 14px; padding: 28px 24px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.08); width: 100%; max-width: 1100px; margin-bottom: 20px;
    }
    .header-row { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 10px; margin-bottom: 16px; }
    h1 { margin: 0; font-size: 1.5em; color: #1a1a2e; }
    .badge { font-size: 0.78em; font-weight: 600; padding: 3px 12px; border-radius: 20px; }
    .badge-live { background:#e8f5e9; color:#2e7d32; border:1px solid #a5d6a7; }
    .badge-demo { background:#fff8e1; color:#f57f17; border:1px solid #ffe082; }
    .signal { font-size: 1.3em; font-weight: 700; padding: 12px 20px; border-radius: 10px; display: inline-block; margin-bottom: 12px; }
    .buy  { background:#e8f5e9; color:#2e7d32; border:1px solid #a5d6a7; }
    .sell { background:#ffebee; color:#c62828; border:1px solid #ef9a9a; }
    .err  { background:#f5f5f5; color:#555;    border:1px solid #ddd; }
    .metrics-row { display:flex; gap:14px; flex-wrap:wrap; margin-bottom: 16px; }
    .metric-pill { background:#f5f7fa; border:1px solid #e0e4e9; border-radius:8px; padding:6px 12px; font-size:0.82em; color:#444; }
    .meta { font-size:0.82em; color:#888; margin-bottom:18px; }
    form { display:inline; }
    button {
      padding: 8px 18px; font-size: 13px; border: none; border-radius: 6px;
      background: #1565c0; color: #fff; cursor: pointer; transition: background 0.15s;
    }
    button:hover { background: #0d47a1; }
    .error-box {
      background: #ffebee; color: #b71c1c; border: 1px solid #ef9a9a; border-radius: 8px;
      padding: 16px; margin-top: 12px; white-space: pre-wrap; font-size: 0.9em;
    }
    .disclaimer { font-size: 0.75em; color: #bbb; text-align: center; margin-top: 8px; }
    .chart-wrap { margin-bottom: 10px; }
  </style>
  <meta http-equiv="refresh" content="30">
</head>
<body>
<div class="card">
  <div class="header-row">
    <h1>EURUSD LSTM Dashboard</h1>
    <span class="badge {{ badge_class }}">{{ source_label }}</span>
  </div>

  {% if error %}
    <div class="signal err">Prediction unavailable</div>
    <div class="error-box">{{ error }}</div>
    <div class="meta">
      <form method="post" action="/refresh"><button type="submit">Run Prediction Now</button></form>
    </div>
  {% else %}
    <div class="signal {{ signal_class }}">{{ signal_text }}</div>
    <div class="metrics-row">
      <span class="metric-pill">Backtest MAE: {{ mae }}</span>
      <span class="metric-pill">Backtest RMSE: {{ rmse }}</span>
      <span class="metric-pill">Directional accuracy: {{ dir_acc }}</span>
    </div>
    <div class="meta">
      Generated: {{ generated_at }} &nbsp;&middot;&nbsp;
      Auto-refreshes every {{ refresh_interval }}s in the background
      &nbsp;&middot;&nbsp;
      <form method="post" action="/refresh"><button type="submit">Refresh Now</button></form>
    </div>
    <div class="chart-wrap">{{ price_chart | safe }}</div>
    <div class="chart-wrap">{{ pct_chart   | safe }}</div>
  {% endif %}

  <div class="disclaimer">
    Model: single-layer LSTM &middot; hidden=100 &middot; trained on EURUSD M15 &nbsp;&middot;&nbsp;
    Prices shown are <em>normalised</em> (0-1 within each trading day) &nbsp;&middot;&nbsp;
    Educational / portfolio project only &mdash; not financial advice.
  </div>
</div>
</body>
</html>
"""


def render_page(error=None):
    results, load_err = load_results()
    error = error or load_err

    if error or results is None:
        return render_template_string(
            PAGE_TEMPLATE, error=error, badge_class="badge-demo", source_label="No data",
            signal_class="err", signal_text="", price_chart="", pct_chart="", generated_at="",
        )

    pct_num = float(results.get("percent_change", 0.0))
    is_buy = pct_num > 0
    signal_text = (
        f"Predicted UP  ·  Next change: +{pct_num:.5f}%" if is_buy
        else f"Predicted DOWN  ·  Next change: {pct_num:.5f}%"
    )
    source = results.get("data_source", "")
    is_live = "metatrader" in source.lower()
    price_chart, pct_chart = build_charts(results)

    mae = results.get("mae")
    rmse = results.get("rmse")
    dir_acc = results.get("directional_accuracy")

    return render_template_string(
        PAGE_TEMPLATE,
        error=None,
        badge_class="badge-live" if is_live else "badge-demo",
        source_label=("Live · " if is_live else "Demo · ") + source,
        signal_class="buy" if is_buy else "sell",
        signal_text=signal_text,
        mae=f"{mae:.5f}" if mae is not None else "n/a",
        rmse=f"{rmse:.5f}" if rmse is not None else "n/a",
        dir_acc=f"{dir_acc * 100:.1f}%" if dir_acc is not None else "n/a",
        price_chart=price_chart,
        pct_chart=pct_chart,
        generated_at=results.get("generated_at", ""),
        refresh_interval=REFRESH_INTERVAL_SECONDS,
    )


@app.route("/")
def index():
    return render_page()


@app.route("/health")
def health():
    return jsonify(status="ok")


@app.route("/refresh", methods=["POST"])
def refresh():
    run_prediction_job()
    return redirect(url_for("index"))


def start_scheduler():
    scheduler = BackgroundScheduler(daemon=True)
    scheduler.add_job(run_prediction_job, "interval", seconds=REFRESH_INTERVAL_SECONDS, next_run_time=datetime.now())
    scheduler.start()
    return scheduler


# Start the background scheduler once, whether this module is run directly
# (python app.py) or imported by a WSGI server (gunicorn app:app).
_scheduler = start_scheduler()


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5001))
    print("=" * 55)
    print("  EURUSD LSTM Dashboard (Plotly edition)")
    print(f"  Open http://127.0.0.1:{port} in your browser")
    print("=" * 55)
    app.run(debug=False, host="0.0.0.0", port=port)
